Repository numerique-gouv/vitrine-eidas, pull requests merged in 2024-06, with the labels that each got.

#5 Ajoute un bouton FranceConnect aux normes
  public/assets/images/franceconnect-btn-principal-hover.svg
  public/assets/images/franceconnect-btn-principal.svg
  public/assets/images/square.svg
  public/assets/styles/pageAccueil.css
  src/siteVitrine.js
  src/vues/pageAccueil.mustache
Labels: enhancement

#6 Ajoute les scopes birthdate birthplace à la requête
  src/api/creationSessionFCPlus.js
  test/api/creationSessionFCPlus.spec.js
Labels: enhancement

#8 Exclus des vérifications eslint le répertoire nginx
  .eslintignore
Labels: bug

#10 [CORRECTION] Nomme onglet « Vitrine eIDAS-France »
  src/vues/pageAccueil.mustache
Labels: bug

#12 Redirection depuis navigateur
  src/routes/routesAuth.js
  test/routes/routesAuth.spec.js
Labels: bug

#13 [REMANIEMENT] Déplace code HTML servi dans page Mustache
  .eslintrc.js
  src/api/connexionFCPlus.js
  src/api/creationSessionFCPlus.js
  src/routes/middleware.js
  src/routes/routesAuth.js
  src/routes/utils.js
  src/vues/redirectionNavigateur.mustache
  test/api/connexionFCPlus.spec.js
  test/api/creationSessionFCPlus.spec.js
  test/routes/middleware.spec.js
Labels: code

#9 Utilise fonte Marianne
  public/assets/fontes/Marianne-Bold.woff
  public/assets/fontes/Marianne-Bold.woff2
  public/assets/fontes/Marianne-Bold_Italic.woff
  public/assets/fontes/Marianne-Bold_Italic.woff2
  public/assets/fontes/Marianne-ExtraBold.woff
  public/assets/fontes/Marianne-ExtraBold.woff2
  public/assets/fontes/Marianne-ExtraBold_Italic.woff
  public/assets/fontes/Marianne-ExtraBold_Italic.woff2
  public/assets/fontes/Marianne-Light.woff
  public/assets/fontes/Marianne-Light.woff2
  public/assets/fontes/Marianne-Light_Italic.woff
  public/assets/fontes/Marianne-Light_Italic.woff2
  public/assets/fontes/Marianne-Medium.woff
  public/assets/fontes/Marianne-Medium.woff2
  public/assets/fontes/Marianne-Medium_Italic.woff
  public/assets/fontes/Marianne-Medium_Italic.woff2
  public/assets/fontes/Marianne-Regular.woff
  public/assets/fontes/Marianne-Regular.woff2
  public/assets/fontes/Marianne-Regular_Italic.woff
  public/assets/fontes/Marianne-Regular_Italic.woff2
  public/assets/fontes/Marianne-Thin.woff
  public/assets/fontes/Marianne-Thin.woff2
  public/assets/fontes/Marianne-Thin_Italic.woff
  public/assets/fontes/Marianne-Thin_Italic.woff2
  public/assets/styles/fontes.css
  public/assets/styles/pageAccueil.css
  src/vues/pageAccueil.mustache
Labels: enhancement

#18 Améliore le bouton de Connexion eIDAS
  public/assets/images/bouton_eidas.png
  public/assets/images/bouton_eidas.svg
  public/assets/images/bouton_survol_eIDAS.svg
  public/assets/styles/pageAccueil.css
Labels: enhancement

#20 Introduis objet métier `Utilisateur`
  src/modeles/sessionFCPlus.js
  src/modeles/utilisateur.js
  src/routes/middleware.js
  src/vues/accueil.pug
  test/modeles/sessionFCPlus.spec.js
  test/modeles/utilisateur.spec.js
  test/routes/middleware.spec.js
  test/routes/routesAuth.spec.js
  test/routes/routesBase.spec.js
Labels: code

#21 Ajout entête et pied-de-page
  public/assets/images/devise.svg
  public/assets/images/logo-eidas.png
  public/assets/images/marianne.svg
  public/assets/styles/commun.css
  src/vues/base.pug
Labels: enhancement

#22 Ajoute un bandeau titre sur la page accueil
  public/assets/images/image-site-vitrine.png
  public/assets/styles/accueil.css
  public/assets/styles/commun.css
  src/vues/accueil.pug
  src/vues/base.pug
Labels: enhancement

#23 Change formulations page accueil
  src/vues/accueil.pug
  test/routes/routesBase.spec.js
Labels: enhancement

#24 Précharge les images de survol
  src/vues/accueil.pug
Labels: enhancement

#25 Utilise un pictogramme de cadenas pour la page d'accueil
  public/assets/images/cadenas.svg
  public/assets/images/image-site-vitrine.png
  public/assets/styles/accueil.css
Labels: enhancement

#26 Introduis un fichier de palette de couleurs réutilisables
  public/assets/styles/accueil.css
  public/assets/styles/commun.css
  public/assets/styles/palette.css
  src/vues/base.pug
Labels: enhancement

#27 Affichage du bouton eIDAS uniquement
  src/vues/accueil.pug
  test/routes/routesBase.spec.js
Labels: enhancement

#28 [CORRECTION] dimensions boutons de connexion
  public/assets/styles/accueil.css
  src/vues/accueil.pug
Labels: bug

#30 [CORRECTION] Sur erreur transmise par FC+, redirection vers page accueil
  src/routes/routesAuth.js
  test/routes/routesAuth.spec.js
Labels: bug

#29 Changement du lien en pied-de-page
  src/vues/base.pug
Labels: bug

#31 [CORRECTION] Pas d'utilisateur courant si processus authent interrompu
  src/erreurs.js
  src/modeles/utilisateur.js
  test/modeles/utilisateur.spec.js
  test/routes/middleware.spec.js
  test/routes/routesBase.spec.js
Labels: bug

#32 Extrais les logos dans un fragment
  public/assets/styles/commun.css
  public/assets/styles/eidas.css
  public/assets/styles/republiqueFrancaise.css
  src/vues/base.pug
  src/vues/fragments/blocMarque.pug
Labels: code
